// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "tank I":return img`
....................
...fffffffffffff....
...fffffffffffff....
..fffffffffffff.....
..fffffffffffff.....
..fffffffffffff.....
..fffffffefffff.....
..ffffeeeeefff......
......eeeeeee.......
.....eeeeeeee.......
......eeeeeee.......
.......e7eee........
........777.........
........777.........
........777.........
........777.........
........777.........
....................
....................
....................
....................
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
